name: Validate Files

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_JSONS: /pokeapi.json
          INPUT_SCHEMA: /schema.json
